name: Capture Screenshot

on:
  schedule:
    - cron: "0 0 * * *"  # Run every day at midnight
  push:
    branches:
      - main  # Run on push to the main branch
  workflow_dispatch:  # Allow manual triggering from the GitHub Actions UI

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Set up Node.js environment
        with:
          node-version: '20'  # Use Node.js version 20

      - name: Install dependencies
        run: npm install  # Install Node.js dependencies

      - name: Run Puppeteer script
        run: node screenshot.js  # Run Puppeteer script to take a screenshot

      - name: Create directory for screenshots
        run: mkdir -p screenshots  # Create directory for screenshots if it doesn't exist

      - name: Move screenshot to directory
        run: |
          if [ -f badge.png ]; then
            mv badge.png screenshots/badge.png
            echo "Screenshot moved to screenshots directory."
          else
            echo "badge.png not found."
          fi

      - name: Commit screenshot to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Create a new branch for the screenshot update
          git checkout -b update-screenshot

          # Add and commit new screenshot
          git add screenshots/badge.png
          git commit -m "Update screenshot" || echo "No changes to commit"

          # Push changes to the temporary branch
          git push origin update-screenshot

          # Merge the temporary branch into the main branch
          git checkout main
          git pull origin main
          git merge update-screenshot

          # Push changes to the main branch
          git push origin main

          # Clean up the temporary branch
          git branch -d update-screenshot

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v3  # Upload the screenshot as an artifact
        with:
          name: screenshots
          path: screenshots/badge.png
