name: Capture Screenshot

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean old artifacts
        run: rm -rf screenshots badge.png

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: node screenshot.js

      - name: Create directory for screenshots
        run: mkdir -p screenshots

      - name: Move screenshot to directory
        run: mv badge.png screenshots/

      - name: Commit screenshot to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b update-screenshot || git checkout update-screenshot
          git add screenshots/badge.png
          git commit -m "Update screenshot" || echo "No changes to commit"
          git push origin update-screenshot --force

      - name: Merge updates to main branch
        run: |
          git checkout main
          git pull origin main
          git merge update-screenshot
          git push origin main
          git branch -d update-screenshot

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/badge.png
