name: Capture Screenshot

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  push:
    branches:
      - main  # Run on push to the main branch
  workflow_dispatch:  # Allow manual triggering from the GitHub Actions UI

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the latest LTS version or specify your desired version

      - name: Install dependencies
        run: npm install

      - name: Install Devanagari fonts
        run: sudo apt-get install -y fonts-noto

      - name: Run Puppeteer script
        run: node screenshot.js

      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: badge
          path: badge.png
