name: Capture Screenshot

on:
  schedule:
     - cron: "0 0 * * *"
  push:
    branches:
      - main  # Run on push to the main branch
  workflow_dispatch:  # Allow manual triggering from the GitHub Actions UI

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated version
        with:
          node-version: '20'  # Use Node.js 20 as recommended

      - name: Install dependencies
        run: npm install

      - name: Install Devanagari fonts
        run: sudo apt-get install -y fonts-noto

      - name: Run Puppeteer script
        run: |
          node screenshot.js
          echo "Screenshot script completed."

      - name: Create directory for screenshots
        run: |
          mkdir -p screenshots
          echo "Directory created: $(ls -l)"

      - name: Move screenshot to directory
        run: |
          if [ -f badge.png ]; then
            mv badge.png screenshots/badge.png
            echo "Screenshot moved to screenshots directory."
          else
            echo "badge.png not found."
          fi

      - name: Commit screenshot to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add screenshots/badge.png
          git commit -m "Add new screenshot"
          git push origin main

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4  # Updated version
        with:
          name: screenshots
          path: screenshots/badge.png
